version: '3.8'
services:
  frontend:
    image: mailbyms/reportbuilder-frontend
    container_name: reportbuilder-frontend
    ports:
      - "5174:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
  backend:
    image: mailbyms/reportbuilder-backend
    container_name: reportbuilder-backend
    ports:
      - "13001:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=reportbuilder
      - DB_PORT=3306
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy

networks:
  default:
    external: true
    name: alarmagent_default

